frontend:
  template_batch:
    filename: batch_template.parquet
    local_dir: ./data/check/batches/

host_aliases:
  train:
    host:
      alias: TRAIN_SERVICE_HOST
      default: '127.0.0.1'
    port:
      alias: TRAIN_SERVICE_PORT
      default: 18507
  predict:
    host:
      alias: PREDICT_SERVICE_HOST
      default: '127.0.0.1'
    port:
      alias: PREDICT_SERVICE_PORT
      default: 9940

endpoints:
  train: ['train', 'dataset', 'config', 'verify', 'train_config', 'preprocessing_config', 'metrics', 'joblib', 'train_status', 'train_health']
  predict: ['predict', 'predict_input', 'evaluate_config', 'predict_health']
