apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "model-pvc.fullname" . }}
spec:
  storageClassName: yc-network-hdd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
