---
global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'streamlit'
    static_configs:
      - targets:
        - 'streamlit:8001'

  - job_name: 'predict'
    static_configs:
      - targets:
        - 'predict:9940'

  - job_name: 'train'
    static_configs:
      - targets:
        - 'train:18507'
  
  - job_name: 'mongodb_exporter'
    static_configs:
    - targets: ['mongodb-exporter:9216']

