name: ${APP_NAME}
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    networks:
      - back_net
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  train:
    build: ../icecube/train/
    image: ${USERNAME}/${APP_NAME}-train:${APP_VERSION}
    depends_on:
      - mongodb
    # ports:
    #   - 18507:18507
    networks:
      - back_net
      - front_net
    container_name: train
    volumes:
      - ../icecube/train/data:/app/data
      - ../icecube/train/config:/app/config
      - ../icecube/train/models:/app/models

  predict:
    build: ../icecube/predict/
    image: ${USERNAME}/${APP_NAME}-predict:${APP_VERSION}
    depends_on:
      - mongodb
    # ports:
    #   - 9940:9940
    networks:
      - back_net
      - front_net
    container_name: predict
    volumes:
      - ../icecube/predict/data:/app/data
      - ../icecube/predict/config:/app/config

  streamlit:
    build: ../icecube/frontend/
    image: ${USERNAME}/${APP_NAME}-streamlit:${APP_VERSION}
    depends_on:
      - train
      - predict
    ports:
      - ${FRONT_PORT}:8501
    networks:
      - front_net
    container_name: streamlit
    volumes:
        - ../icecube/frontend/data:/app/data
        - ../icecube/frontend/config:/app/config

  prometheus:
    build: ../prometheus/
    image: ${USERNAME}/prometheus
    depends_on:
      - streamlit
      - train
      - predict
    networks:
      - back_net
      - front_net
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день

  mongodb_exporter:
    image: percona/mongodb_exporter:0.20
    networks:
      - back_net
      - front_net
    container_name: mongodb-exporter
    # ports:
    #   - 9216:9216
    command:
      - '--mongodb.uri=mongodb://${DB_USER}:${DB_PASSWORD}@mongodb:27017'

volumes:
  mongodb:
  prometheus_data:

networks:
  front_net:
  back_net:
