---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "train.fullname" . }}
  labels:
    app: icecube
    component: train
    release: {{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: icecube
      component: train
      release: {{ .Release.Name }}
  template:
    metadata:
      name: train
      labels:
        app: icecube
        component: train
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: train
        env:
        - name: TRAIN_DATABASE_HOST
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
