global:
  resolve_timeout: 10s

route:
  group_by: ['alertname']
  group_wait: 3s
  receiver: 'telegram_bot'

receivers:
- name: 'telegram_bot'
  telegram_configs:
  - bot_token: '7334316533:AAEDbolcgf_h7YFvmFKqtIkD7uAJYe-54_4'
    api_url: 'https://api.telegram.org'
    chat_id: 1399476130
    parse_mode: 'HTML'
